### ISSUE TITLE
lpu230 keylock SO v1.14.1

### ISSUE THREAD

**Issue by elpusk** [elpusk/public.lpu237.software#2]
BinaryConversion setter 호출시 exception 발생.
POS for .Net 에서 ElectronicKeyValue 에 저장되는  data encoding 문제가 있는 듯
7a  00 00 15  52  c8  9d  01  값이 81 00 00 15 52 38  a4 01 로 encoding 됨.

**Comment by elpusk006** [comment]
set BinaryConversion 호출을 지원하지 않는다는 의미에서 BinaryConversion setter 호출시, exception 발생 시켰으나
UnifiedPOS Version 1_14_1_20141023.pdf spec 문서에 따라 OposLpu230Lock.dll(lpu230 keylock SO) v1.14.2 에서 exception 발생 없이 처리 가능하도록 수정함.

또한 v1.14.1 에서 발견된 다른 missing code 로
getElectricKeyValue() 호출시, 잘못된 형식으로 key 값을 반환하는 문제도 v1.14.2에서 같이 해결 할 수있도록함.

그러나, 기존 사용자 호환성을 유지하기 위해 [설정파일](https://github.com/elpusk/public.lpu237.software/wiki/OposLpu230Lock.dll) 로 기존 v1.14.1 처럼 동작 할지, 수정된 v1.14.2 처럼 동작 할지 결정 할 수 있도록 함. 물론 기본 값은 v1.14.1 처럼 동작하는 것임.
