### ISSUE TITLE
ng_devmgmt bug

### ISSUE THREAD

**Issue by elpusk006** [elpusk/public.lpu237.software#3]
ng_devmgmt 가 일부 PC에서 시작하면서 MSR 장비를 인식하지 못한다.
OS 부팅 직 후에 발생한다.

**Comment by ssyang** [comment]
Ndm. 장비 인식 문제는 드라이버 로드보다 먼저 ndm이 동작되서 발생하는 문제 일 수 맀다 즉일정 주기로 강제 장비 찾기 기능이 있으면 해결 될 둣하다

**Comment by elpusk006** [comment]
﻿
NDM 의 구성 요소 중 ng_DDL_lpu237.dll 를 버전 1.0 에서 1.1 로 업데이트 하면서 해결됨.(installer v1.8.67)

확인된 원인
ng_DDL_lpu237.dll 에서 연결된 장비의 vid, pid 를 얻기 위해  windows API 함수 HidD_GetAttributes() 호출시,  usb vid 0x32d7, pid 0x0010 장치에서 오류가 발생하여, ng_DDL_lpu237.dll 은 장비 찾기를 중단함.


수정된 부분
HidD_GetAttributes() 가 에러를 발생해도, 에러 발생한 장비만 무시하고, 계속 장비 찾기를 계속하도록 수정.


﻿
