### ISSUE TITLE
lpu237_setting_file_x_004 에서

### ISSUE THREAD

**Issue by elpusk** [elpusk/public.lpu237.software#4]
lpu237 의 설정 파일에서 
language attribute 의 가능한 value 값에
"turkiye" 도 추가 되었으나 이 들 문서에서는 아직도 
"turkey" 만 가능한 것으로 표시되어 있음.
다음  lpu237_setting_file_x_005 에서 추가 바람.

**Comment by elpusk006** [comment]
mapper v1.47.0.4 배포 할 때 수정해서 배포 예정. 수정은 완료.
